### ISSUE TITLE
What is SAM filter?

### ISSUE THREAD

**Issue by LinLin1031** [GAP-LAB-CUHK-SZ/SAMPro3D#2]
Thanks for your excellent work. Can you please tell me what is the filtering strategy in automatic-SAM mentioned in the paper? I didn't find the filtering strategy in _[segment anything](https://github.com/facebookresearch/segment-anything)_.

**Comment by mutianxu** [comment]
Hi,

Thanks for your attention!

We have provided some descriptions of this filter in our supplementary material. We made some revisions based on the code starting from https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/automatic_mask_generator.py#L294.

Our code will be public around the end of Dec.
