### ISSUE TITLE
Some bugs.

### ISSUE THREAD

**Issue by LinLin1031** [GAP-LAB-CUHK-SZ/SAMPro3D#4]
Hello! 

Thank you for your wonderful work. I have encountered the following two bugs in my reproduction, in which I have not changed any core code.

The first bug I encountered was when I followed the steps to run "main.py":
![image](https://github.com/GAP-LAB-CUHK-SZ/SAMPro3D/assets/50825626/c1813c05-5fe8-4717-b272-934b2674d7d7)
https://github.com/GAP-LAB-CUHK-SZ/SAMPro3D/blob/2733583ebe861912cb214fe7fd11e244989737bd/main.py#L165
I solved the problem by modifying line 165:
`mask_2d_3d = mask[mapping[:, 0].type(torch.long), mapping[:, 1].type(torch.long)]`

I encountered the second bug after resolving the first one:
![image](https://github.com/GAP-LAB-CUHK-SZ/SAMPro3D/assets/50825626/c454e2b3-6b3f-4b70-8421-10bb6ad02f5e)
So I fixed the bug by moving line 377 before line 358.
https://github.com/GAP-LAB-CUHK-SZ/SAMPro3D/blob/2733583ebe861912cb214fe7fd11e244989737bd/main.py#L377

Hope these get your attention. @mutianxu

**Comment by mutianxu** [comment]
Thanks for your interest!

For the first issue, the original code runs well on my computer. I guess it may be the problem with pytorch version.

For the second issue, it has been fixed!

Thanks!
