### ISSUE TITLE
How can I visualize 3D bounding boxes?

### ISSUE THREAD

**Issue by libaiwanovo** [GAP-LAB-CUHK-SZ/SAMPro3D#5]
Thank you and your team for the wonderful work! I've successfully run the code, but how can I visualize the 3D bounding boxes?

**Comment by mutianxu** [comment]
As stated in the README, "After finishing this, the visualization result of the final 3D segmentation will be automatically 😊 saved as sceneXXXX_XX.ply file in the path specified by --output_vis_path".

This is a result visualization with the point-level segmentation mask.

As for the bounding box (detection task), we do not support it so far.

However, you may generate by yourself, simply by setting the [x_min, x_max, y_min, y_max, z_min, z_max] of an instance segmentation area as the bounding box of this instance.

**Comment by libaiwanovo** [comment]
Thank you for your advice; I will continue to try.
