### ISSUE TITLE
Poor result on scannet

### ISSUE THREAD

**Issue by liuxuexun** [GAP-LAB-CUHK-SZ/SAMPro3D#8]
Thank you for openning your great work!

I use your code and run on scene0000_00, here is the result.

![1](https://github.com/user-attachments/assets/31e77b7c-2395-45e5-a9c4-4237aabf6b41)
![2](https://github.com/user-attachments/assets/29b39442-b651-47e4-a622-49bc14b75c67)

I think the result is too poor, is my result normal?

**Comment by mutianxu** [comment]
Hi, thanks for your interest!

According to your result, I don't think the result is poor, actually.

Our mehod is a zero-shot method, and your results show that it has succesfully segmented the instance or part.

Please do not compare the results with GT, as GT does not provide fine-grained annotations.

**Comment by liuxuexun** [comment]
Thanks for your reply!

Actually, the result is already good!

By the way, I want to know whether you test your method on class-agnostic 3D instance segmentation task on the scannet val set? 

What about AP/AP50/AP25 score? I only see mIoU in the paper.

Thank you.

**Comment by mutianxu** [comment]
We will update the paper to provide the AP scores in the future (but may not very soon), before the meeting of 3DV 2025.

**Comment by ahme0307** [comment]
@liuxuexun, I am getting poor results on scannet(similar to yours). Did you find optimal parameters for best performance? 

<img width="2574" height="1079" alt="Image" src="https://github.com/user-attachments/assets/15f2dd81-211e-4075-82e0-4ee10cfc6e54" />
